### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by 0x41414141** [3lpsy/boucanpy#2]
Hi,

This looks like a cool project i'd like to use & potentially contribute to; this repo (and the related boucan projects) do not seem to have a license chosen however; as such I am limited to forking and reading the code. Would you be able to choose a license to indicate how you expect the code/attributions to be handled please :-)

Please see https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license for guidance.

Thanks

**Comment by 3lpsy** [comment]
Added :) Thanks!
